### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by salimbene** [jalder/openshift-templates#3]
Hey John,

Have you experience access errors like the one below? I'm running your openshift template for Mongo-dbcharts updated to use 19.12.2 image, but I'm not getting past this error. This is happening on Openshift 4.3.

Thanks by your article BTW, I was trying to get mongodb-charts working on openshift manually but it seems that is not supported. Cheers.

```bash

 ✔ parsedArgs 
 ✔ installDir ('/mongodb-charts')
 ✔ log 
 ✔ salt 
 ✔ productNameAndVersion ({ productName: 'MongoDB Charts Frontend', version: '1.9.1' })
 ✔ gitHash ('1a46f17f')
 ✔ supportWidgetAndMetrics ('on')
 ✔ tileServer (undefined)
 ✔ tileAttributionMessage (undefined)
 ✔ rawFeatureFlags (undefined)
 ✔ chartsMongoDBUri 
 ✔ encryptionKeyPath 
 ✔ stitchMigrationsLog ({ completedStitchMigrations: [] })
 ✔ featureFlags ({})
events.js:174
      throw er; // Unhandled 'error' event
      ^


Error: EACCES: permission denied, open '/mongodb-charts/logs/charts-cli.log'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```
![image](https://user-images.githubusercontent.com/39461326/85042777-fb0b7e80-b161-11ea-93ba-6695754c1a37.png)

**Comment by jalder** [comment]
Hi Matias,
The MongoDB Charts docker image runs with root UID within the container.  On OpenShift platforms, this will lead to issues when the randomly assigned UID is used instead.   For testing purposes, I have successfully moved the SCC for the deployment to a less restrictive context that allows running processes with root.

I know that isn't ideal, so I started a second (unsupported) test project that builds off the base MongoDB Charts image to run with a different UID.
https://github.com/jalder/mongodb-charts-noroot
This would require that you build the docker image using the repo above, place it in your own image registry, and then use that image rather than the MongoDB Charts image from quay.

Let me know if I can clarify any of the above or if you have any thoughts on the alternative solutions.

**Comment by salimbene** [comment]
Thanks John. I'm currently deploying it, looks good so far. But just a couple of questions, does this deployment also creates Mongo DB for the metadata, or should I create it separately and connect both pods? Looking at the docker file I don't see an ENV var to handle the MongoDB URI of the metadata DB, so I'm not sure how to handle it. Thanks again for your help!

**Comment by salimbene** [comment]
The deployment from image, create two pods, one of which is running fine:

 ✔ parsedArgs 
 ✔ installDir ('/mongodb-charts')
 ✔ log 
 ✔ salt 
 ✔ productNameAndVersion ({ productName: 'MongoDB Charts Frontend', version: '1.9.1' })
 ✔ gitHash ('1a46f17f')
 ✔ supportWidgetAndMetrics (undefined)
 ✔ tileServer (undefined)
 ✔ tileAttributionMessage (undefined)
 ✔ rawFeatureFlags (undefined)
 ✔ stitchMigrationsLog ({ completedStitchMigrations: [] })
 ✔ featureFlags ({})
(node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
 ✖ chartsMongoDBUri failure: ENOENT: no such file or directory, open '/run/secrets/charts-mongodb-uri'
 ✔ lastAppJson ({})
 ✔ tokens 
 ✔ encryptionKeyPath 
 ✔ stitchConfigTemplate 
 ✔ libMongoIsInPath (true)

Although I cannot access it via the automatically created service/route, it does work on port 80 right?

![image](https://user-images.githubusercontent.com/39461326/85750922-81830b80-b6e0-11ea-9003-7c0c7cd4f45a.png)
